# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-22 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendedorBiable',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('linea', models.PositiveIntegerField(choices=[(1, 'Freshman'), (2, 'Sophomore'), (3, 'Junior'), (4, 'Sin Definir')])),
            ],
        ),
    ]
