# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-22 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biable', '0002_vendedorbiable'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoVentaBiable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_vendedor', models.PositiveIntegerField()),
                ('id_terc_fa', models.CharField(max_length=20)),
                ('cliente', models.CharField(max_length=200)),
                ('proyecto', models.CharField(max_length=10)),
                ('item_id', models.PositiveIntegerField()),
                ('precio_uni', models.DecimalField(decimal_places=4, max_digits=18)),
                ('fecha', models.DateTimeField()),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=18)),
                ('venta_bruta', models.DecimalField(decimal_places=4, max_digits=18)),
                ('dscto_netos', models.DecimalField(decimal_places=4, max_digits=18)),
                ('costo_total', models.DecimalField(decimal_places=4, max_digits=18)),
                ('rentabilidad', models.DecimalField(decimal_places=4, max_digits=18)),
                ('imp_netos', models.DecimalField(decimal_places=4, max_digits=18)),
                ('venta_neto', models.DecimalField(decimal_places=4, max_digits=18)),
            ],
        ),
        migrations.AlterField(
            model_name='vendedorbiable',
            name='id',
            field=models.PositiveIntegerField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vendedorbiable',
            name='linea',
            field=models.PositiveIntegerField(choices=[(1, 'Proyectos'), (2, 'Bandas y Componentes'), (3, 'Posventa'), (4, 'Sin Definir')], default=4),
        ),
    ]
