# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-22 16:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biable', '0003_auto_20161122_1138'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataBiable',
        ),
    ]
