# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-23 16:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biable', '0004_delete_databiable'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoventabiable',
            name='vendedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='biable.VendedorBiable'),
        ),
    ]
