# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-25 13:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biable', '0005_movimientoventabiable_vendedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientoventabiable',
            name='id_vendedor',
        ),
    ]
