# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-25 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biable', '0006_remove_movimientoventabiable_id_vendedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientoventabiable',
            name='fecha',
        ),
        migrations.AddField(
            model_name='movimientoventabiable',
            name='day',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movimientoventabiable',
            name='month',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movimientoventabiable',
            name='year',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
