# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-25 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biable', '0007_auto_20161125_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoventabiable',
            name='day',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='movimientoventabiable',
            name='month',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='movimientoventabiable',
            name='year',
            field=models.PositiveIntegerField(),
        ),
    ]
