# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('biable', '0011_auto_20161202_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendedorBiableUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_vendedores', to='usuarios.UserExtended')),
                ('vendedores', models.ManyToManyField(related_name='mis_auditores', to='biable.VendedorBiable')),
            ],
        ),
    ]
