# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-28 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biable', '0015_auto_20161220_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedorbiable',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
