# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-28 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biable', '0017_auto_20161228_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineaVendedorBiable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
            ],
        ),
    ]
