# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-28 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biable', '0018_lineavendedorbiable'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedorbiable',
            name='linea_ventas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mis_vendedores', to='biable.LineaVendedorBiable'),
        ),
    ]
