# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biable', '0024_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='id',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nit',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
