# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-04 18:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biable', '0025_auto_20170103_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartera',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='biable.Cliente'),
        ),
    ]
