# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-04 23:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biable', '0031_auto_20170104_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendedorbiableuser',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='vendedorbiableuser',
            name='vendedores',
        ),
        migrations.DeleteModel(
            name='VendedorBiableUser',
        ),
    ]
