# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 14:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('biable', '0032_auto_20170104_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturasBiable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('day', models.PositiveIntegerField()),
                ('tipo_documento', models.CharField(blank=True, max_length=3, null=True)),
                ('nro_documento', models.CharField(blank=True, max_length=10, null=True)),
                ('venta_bruta', models.DecimalField(decimal_places=4, max_digits=18)),
                ('dscto_netos', models.DecimalField(decimal_places=4, max_digits=18)),
                ('costo_total', models.DecimalField(decimal_places=4, max_digits=18)),
                ('rentabilidad', models.DecimalField(decimal_places=4, max_digits=18)),
                ('imp_netos', models.DecimalField(decimal_places=4, max_digits=18)),
                ('venta_neto', models.DecimalField(decimal_places=4, max_digits=18)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='biable.Cliente')),
                ('vendedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='biable.VendedorBiable')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
