# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biable', '0033_facturasbiable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturasbiable',
            name='day',
            field=models.PositiveIntegerField(verbose_name='Día'),
        ),
        migrations.AlterField(
            model_name='facturasbiable',
            name='month',
            field=models.PositiveIntegerField(verbose_name='Mes'),
        ),
        migrations.AlterField(
            model_name='facturasbiable',
            name='year',
            field=models.PositiveIntegerField(verbose_name='Año'),
        ),
    ]
