# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-19 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biable', '0034_auto_20170111_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsBiable',
            fields=[
                ('id_item', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('id_referencia', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=40)),
                ('descripcion_dos', models.CharField(max_length=40)),
                ('activo', models.BooleanField(default=True)),
                ('nombre_tercero', models.CharField(max_length=120)),
                ('desc_item_padre', models.CharField(max_length=40)),
                ('unidad_medida_inventario', models.CharField(max_length=6)),
                ('id_procedencia', models.CharField(max_length=1)),
            ],
        ),
    ]
