# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-19 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biable', '0035_itemsbiable'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoventabiable',
            name='factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mis_movimientos_venta', to='biable.FacturasBiable'),
        ),
    ]
