# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-19 23:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biable', '0037_cartera_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoventabiable',
            name='item_biable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mis_ventas', to='biable.ItemsBiable'),
        ),
    ]
