# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-19 23:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biable', '0038_movimientoventabiable_item_biable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientoventabiable',
            name='item_id',
        ),
    ]
