# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-02 14:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biable', '0042_auto_20170131_1036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimientoventabiable',
            options={'permissions': (('reportes_ventas', 'Reportes Ventas'), ('reporte_ventas_1', 'R Vent Vend'), ('reporte_ventas_2', 'R Conso Ventas'), ('reporte_ventas_3', 'R Vent Cli'), ('reporte_ventas_4', 'R Vent Cli Año'), ('reporte_ventas_5', 'R Vent Cli Mes'), ('reporte_ventas_6', 'R Vent Lin Año'), ('reporte_ventas_7', 'R Vent Lin Año Mes'), ('reporte_ventas_8', 'R Vent Mes'), ('reporte_ventas_9', 'R Vent Vend Mes'), ('reporte_ventas_10', 'R Vent Pro Año Mes'), ('reporte_ventas_todos_vendedores', 'R Vent Vend Todos'))},
        ),
    ]
