# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-02 22:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geografia_colombia', '0004_auto_20170202_1705'),
        ('biable', '0044_auto_20170202_1727'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartera',
            options={'permissions': (('ver_carteras', 'R Cart. Vcto'), ('ver_carteras_todos', 'R Cart. Vcto Todos')), 'verbose_name': 'Cartera', 'verbose_name_plural': 'T-0.3 Carteras'},
        ),
        migrations.AlterModelOptions(
            name='ciudadbiable',
            options={'verbose_name': 'Ciudad', 'verbose_name_plural': 'C-0.3 Ciudades'},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'C-1.1 Clientes'},
        ),
        migrations.AlterModelOptions(
            name='departamentobiable',
            options={'verbose_name': 'Departamento', 'verbose_name_plural': 'C-0.2 Departamentos'},
        ),
        migrations.AlterModelOptions(
            name='facturasbiable',
            options={'permissions': (('ver_info_admon_ventas', 'Ver Info Admon Factura'),), 'verbose_name': 'Factura', 'verbose_name_plural': 'T-0.1 Facturas'},
        ),
        migrations.AlterModelOptions(
            name='itemsbiable',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'C-2.1 Items'},
        ),
        migrations.AlterModelOptions(
            name='lineavendedorbiable',
            options={'verbose_name': 'Linea Vendedor CGUno', 'verbose_name_plural': 'I-0.1 Lineas Vendedor CGUno'},
        ),
        migrations.AlterModelOptions(
            name='movimientoventabiable',
            options={'permissions': (('reportes_ventas', 'Reportes Ventas'), ('reporte_ventas_1', 'R Vent Vend'), ('reporte_ventas_2', 'R Conso Ventas'), ('reporte_ventas_3', 'R Vent Cli'), ('reporte_ventas_4', 'R Vent Cli Año'), ('reporte_ventas_5', 'R Vent Cli Mes'), ('reporte_ventas_6', 'R Vent Lin Año'), ('reporte_ventas_7', 'R Vent Lin Año Mes'), ('reporte_ventas_8', 'R Vent Mes'), ('reporte_ventas_9', 'R Vent Vend Mes'), ('reporte_ventas_10', 'R Vent Pro Año Mes'), ('reporte_ventas_todos_vendedores', 'R Vent Vend Todos')), 'verbose_name': 'Movimiento Venta', 'verbose_name_plural': 'T-0.2 Movimiento Ventas'},
        ),
        migrations.AlterModelOptions(
            name='paisbiable',
            options={'verbose_name': 'País', 'verbose_name_plural': 'C-0.1 Paises'},
        ),
        migrations.AlterModelOptions(
            name='vendedorbiable',
            options={'verbose_name': 'Vendedor', 'verbose_name_plural': 'C-1.2 Vendedores'},
        ),
        migrations.AddField(
            model_name='ciudadbiable',
            name='ciudad_intranet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geografia_colombia.Ciudad'),
        ),
        migrations.AddField(
            model_name='departamentobiable',
            name='departamento_intranet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geografia_colombia.Departamento'),
        ),
        migrations.AddField(
            model_name='paisbiable',
            name='pais_intranet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geografia_colombia.Pais'),
        ),
    ]
