# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-02 23:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biable', '0045_auto_20170202_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamentobiable',
            name='departamento_intranet',
        ),
        migrations.RemoveField(
            model_name='paisbiable',
            name='pais_intranet',
        ),
    ]
