# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-02 23:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biable', '0046_auto_20170202_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturasbiable',
            name='ciudad_biable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='biable.CiudadBiable'),
        ),
        migrations.AddField(
            model_name='facturasbiable',
            name='fecha_documento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
