# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-02 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biable', '0047_auto_20170202_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturasbiable',
            name='proyecto',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
