# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-02 23:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biable', '0048_facturasbiable_proyecto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientoventabiable',
            name='proyecto',
        ),
    ]
