# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-03 13:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biable', '0049_remove_movimientoventabiable_proyecto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturasbiable',
            name='day',
        ),
        migrations.RemoveField(
            model_name='facturasbiable',
            name='month',
        ),
        migrations.RemoveField(
            model_name='facturasbiable',
            name='year',
        ),
    ]
