# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-03 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biable', '0051_facturasbiable_direccion_despacho'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name_plural': 'I-02 Grupos Cliente',
                'verbose_name': 'Grupo Cliente',
            },
        ),
        migrations.AlterModelOptions(
            name='cartera',
            options={'permissions': (('ver_carteras', 'R Cart. Vcto'), ('ver_carteras_todos', 'R Cart. Vcto Todos')), 'verbose_name': 'Cartera', 'verbose_name_plural': 'T-0.2 Carteras'},
        ),
        migrations.AddField(
            model_name='cliente',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mis_empresas', to='biable.GrupoCliente'),
        ),
    ]
