# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-03 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biable', '0052_auto_20170203_1059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grupocliente',
            options={'verbose_name': 'Grupo Cliente', 'verbose_name_plural': 'I-0.2 Grupos Cliente'},
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='created',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='modified',
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_creacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
