# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 21:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biable', '0055_auto_20170206_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='SucursalBiable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_sucursal', models.PositiveIntegerField()),
                ('nombre_establecimiento', models.CharField(blank=True, max_length=200, null=True)),
                ('cupo_credito', models.DecimalField(decimal_places=0, max_digits=10)),
                ('condicion_pago', models.PositiveIntegerField(blank=True, null=True)),
                ('activo', models.BooleanField()),
                ('fecha_creacion', models.DateField()),
                ('direccion', models.CharField(max_length=200)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_sucursales', to='biable.Cliente')),
                ('vendedor_biable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mis_clientes_biable', to='biable.VendedorBiable')),
                ('vendedor_real', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mis_clientes_reales', to='biable.VendedorBiable')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='sucursalbiable',
            unique_together=set([('nro_sucursal', 'cliente')]),
        ),
    ]
