# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biable', '0057_facturasbiable_sucursal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sucursalbiable',
            options={'verbose_name': 'Sucursal Cliente', 'verbose_name_plural': 'C-1.2 Sucursales Cliente'},
        ),
        migrations.AlterModelOptions(
            name='vendedorbiable',
            options={'verbose_name': 'Vendedor', 'verbose_name_plural': 'C-1.3 Vendedores'},
        ),
        migrations.AddField(
            model_name='facturasbiable',
            name='anulada',
            field=models.BooleanField(default=False),
        ),
    ]
