# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 21:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_industria'),
        ('biable', '0059_auto_20170207_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='canal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mis_empresas', to='empresas.Canal'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='clasificacion',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='industria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mis_empresas', to='empresas.Industria'),
        ),
    ]
