# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biable', '0061_cliente_competencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='potencial_compra',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Potencial de Compra'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='potencial_compra_fecha_actualizacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha último Cambio Potencial Compra'),
        ),
    ]
