# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biable', '0063_auto_20170209_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursalbiable',
            name='nombre_establecimiento_intranet',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
