# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biable', '0064_sucursalbiable_nombre_establecimiento_intranet'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cerro',
            field=models.BooleanField(default=False),
        ),
    ]
