# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biable', '0066_auto_20170213_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cliente_nuevo_nit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_viejo_nit', to='biable.Cliente'),
        ),
    ]
