# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 20:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listasprecios', '0001_initial'),
        ('biable', '0067_cliente_cliente_nuevo_nit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='canal',
        ),
        migrations.AddField(
            model_name='cliente',
            name='forma_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mis_empresas', to='listasprecios.FormaPago'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cerro',
            field=models.BooleanField(default=False, verbose_name='Cerró'),
        ),
    ]
