# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 21:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_auto_20170207_1725'),
        ('biable', '0068_auto_20170224_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='forma_pago',
        ),
        migrations.AddField(
            model_name='cliente',
            name='canal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mis_empresas', to='empresas.Canal'),
        ),
    ]
