# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biable', '0069_auto_20170224_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='forma_pago',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Forma Pago CGUno'),
        ),
    ]
