# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0013_contactoempresa_cliente'),
        ('biable', '0070_cliente_forma_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguimientoCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('tipo', models.CharField(choices=[('LLAMADA', 'Llamada'), ('VISITA', 'Visita'), ('CORREO', 'Correo')], max_length=20)),
                ('asunto', models.CharField(blank=True, max_length=150, null=True)),
                ('descripcion', models.TextField()),
                ('fecha_seguimiento', models.DateTimeField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='biable.Cliente')),
                ('contacto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contactos.ContactoEmpresa')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
