# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biable', '0071_seguimientocliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimientocliente',
            name='asunto',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
