# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biable', '0074_auto_20170228_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimientocliente',
            name='fecha_seguimiento',
            field=models.DateField(),
        ),
    ]
