# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biable', '0075_auto_20170228_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='no_vender',
            field=models.BooleanField(default=False, verbose_name='No Vender'),
        ),
    ]
