# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 15:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('biable', '0076_cliente_no_vender'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimientocliente',
            name='creado_por',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
