# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biable', '0078_auto_20170302_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsbiable',
            name='ultimo_costo',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18),
        ),
    ]
