# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 22:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geografia_colombia', '0004_auto_20170202_1705'),
        ('biable', '0061_cliente_competencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactoEmpresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('correo_electronico', models.EmailField(blank=True, max_length=254, null=True)),
                ('correo_electronico_alternativo', models.EmailField(blank=True, max_length=254, null=True)),
                ('nro_telefonico', models.CharField(max_length=120)),
                ('nro_telefonico_alternativo', models.CharField(max_length=120)),
                ('ciudad_alternativa', models.CharField(blank=True, max_length=120, null=True)),
                ('empresa_alternativa', models.CharField(blank=True, max_length=120, null=True)),
                ('nit_alternativo', models.CharField(blank=True, max_length=120, null=True)),
                ('ciudad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mis_contactos', to='geografia_colombia.Ciudad')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mis_contactos', to='biable.Cliente')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_contactos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Contactos Empresas',
                'verbose_name': 'Contacto Empresa',
            },
        ),
    ]
