# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0002_auto_20170207_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactoempresa',
            name='correo_electronico',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
