# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 03:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0003_auto_20170207_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactoCargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('cargo', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='contactoempresa',
            name='retirado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactoempresa',
            name='cargo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mis_contactos', to='contactos.ContactoCargo'),
            preserve_default=False,
        ),
    ]
