# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0004_auto_20170210_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactoempresa',
            name='nro_telefonico_alternativo_dos',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='contactoempresa',
            name='cargo',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='contactoempresa',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mis_contactos', to='biable.SucursalBiable'),
        ),
        migrations.AlterField(
            model_name='contactoempresa',
            name='nro_telefonico',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='contactoempresa',
            name='nro_telefonico_alternativo',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.DeleteModel(
            name='ContactoCargo',
        ),
    ]
