# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 15:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0009_auto_20170211_1046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactoempresa',
            old_name='cliente',
            new_name='sucursal',
        ),
        migrations.RemoveField(
            model_name='contactoempresa',
            name='empresa_alternativa',
        ),
    ]
