# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0011_auto_20170211_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactoempresa',
            name='subempresa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
