# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 17:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biable', '0066_auto_20170213_1208'),
        ('contactos', '0012_contactoempresa_subempresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactoempresa',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mis_contactos', to='biable.Cliente'),
        ),
    ]
