# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0013_contactoempresa_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactoempresa',
            name='correo_electronico',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
