# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-06-14 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dominiosemail',
            options={'verbose_name': 'Dominios Correos Electrónicos'},
        ),
    ]
