# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 14:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('biable', '0033_facturasbiable'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvioTransportadoraTCC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('fecha_envio', models.DateField()),
                ('nro_factura_transportadora', models.PositiveIntegerField(blank=True, null=True)),
                ('nro_tracking', models.CharField(max_length=60)),
                ('cliente_alternativo', models.CharField(blank=True, max_length=60, null=True)),
                ('tipo', models.CharField(choices=[('PQ', 'Paquetería'), ('MS', 'Mensajería')], default='PQ', max_length=2)),
                ('servicio_boom', models.BooleanField(default=False)),
                ('rr', models.BooleanField(default=False)),
                ('forma_pago', models.CharField(choices=[('NOR', 'NORMAL'), ('CTA', 'CUENTA'), ('RD', 'RD'), ('FCE', 'FCE'), ('NA', 'NO VIAJA'), ('9AM', '9AM')], max_length=3)),
                ('observacion', models.TextField(blank=True, max_length=200, null=True)),
                ('estado', models.CharField(choices=[('CP', 'Cumplido parcial del despacho por presentar novedad'), ('DD', 'Descargado en Destino'), ('PE', 'En proceso de entrega'), ('RP', 'En Reparto'), ('EN', 'Entregada'), ('ER', 'Entregada (Retorno Odeco)'), ('NS', 'Novedad Solucionada'), ('RO', 'Recibido en Origen'), ('NA', 'NO FUE ENVIADA')], max_length=2)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=18)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biable.Cliente')),
                ('facturas', models.ManyToManyField(related_name='envios', to='biable.FacturasBiable')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
