# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despachos_mercancias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enviotransportadoratcc',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True),
        ),
    ]
