# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despachos_mercancias', '0002_enviotransportadoratcc_fecha_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enviotransportadoratcc',
            name='facturas',
            field=models.ManyToManyField(blank=True, null=True, related_name='envios', to='biable.FacturasBiable'),
        ),
    ]
