# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despachos_mercancias', '0003_auto_20170111_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enviotransportadoratcc',
            name='rr',
            field=models.BooleanField(default=False, verbose_name='Entregado RR'),
        ),
    ]
