# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-12 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despachos_mercancias', '0005_auto_20170111_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enviotransportadoratcc',
            name='facturas',
            field=models.ManyToManyField(blank=True, related_name='envios', to='biable.FacturasBiable', verbose_name='Facturas'),
        ),
    ]
