# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-13 19:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('despachos_mercancias', '0009_remove_enviotransportadoratcc_servicio_boom'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enviotransportadoratcc',
            options={'permissions': (('ver_segui_envio_tcc', 'Seg. Envios TCC'),)},
        ),
    ]
