# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-13 21:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geografia_colombia', '0002_auto_20170113_1549'),
        ('despachos_mercancias', '0010_auto_20170113_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='enviotransportadoratcc',
            name='ciudad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mis_envios_tcc', to='geografia_colombia.Ciudad'),
        ),
    ]
