# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-17 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despachos_mercancias', '0012_auto_20170113_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='enviotransportadoratcc',
            name='valor_boom',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='enviotransportadoratcc',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
    ]
