# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 20:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('despachos_mercancias', '0013_auto_20170117_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enviotransportadoratcc',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mis_despachos', to='biable.Cliente'),
        ),
    ]
