# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccion',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='transaccion',
        ),
        migrations.AddField(
            model_name='documento',
            name='nro',
            field=models.CharField(default=1, max_length=10, verbose_name='Nro. Documento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mis_documentos', to='documentos.TipoDocumento', verbose_name='Tipo Documento'),
        ),
        migrations.DeleteModel(
            name='Transaccion',
        ),
    ]
