# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 19:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_auto_20170103_1415'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='documento',
            unique_together=set([('tipo', 'nro')]),
        ),
    ]
