# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import documentos.models


class Migration(migrations.Migration):

    dependencies = [
        ('biable', '0024_cliente'),
        ('documentos', '0004_auto_20170103_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipodocumento',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mis_documentos', to='biable.Cliente'),
        ),
        migrations.AlterField(
            model_name='imagendocumento',
            name='imagen',
            field=models.ImageField(upload_to=documentos.models.imagen_documento_upload_to, validators=[documentos.models.ImagenDocumento.validate_image]),
        ),
    ]
