# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biable', '0024_cliente'),
        ('documentos', '0005_auto_20170103_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipodocumento',
            name='cliente',
        ),
        migrations.AddField(
            model_name='documento',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mis_documentos', to='biable.Cliente'),
        ),
    ]
