# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 21:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0006_auto_20170103_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='cliente',
        ),
    ]
