# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-20 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma', models.CharField(max_length=100)),
                ('porcentaje', models.DecimalField(decimal_places=3, default=0, max_digits=18, verbose_name='%')),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.Canal')),
            ],
            options={
                'verbose_name_plural': '1. Formas de Pago',
            },
        ),
        migrations.AlterUniqueTogether(
            name='formapago',
            unique_together=set([('canal', 'forma')]),
        ),
    ]
