# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-20 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColorProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('nomenclatura', models.CharField(max_length=2, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Colores Productos',
                'verbose_name': 'Color Producto',
            },
        ),
        migrations.CreateModel(
            name='FabricanteProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('nomenclatura', models.CharField(max_length=2, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Fabricantes Productos',
                'verbose_name': 'Fabricante Producto',
            },
        ),
        migrations.CreateModel(
            name='MaterialProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('nomenclatura', models.CharField(max_length=2, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Materiales Productos',
                'verbose_name': 'Material Producto',
            },
        ),
        migrations.CreateModel(
            name='SerieProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('nomenclatura', models.CharField(max_length=6, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Series Productos',
                'verbose_name': 'Serie Producto',
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('nomenclatura', models.CharField(max_length=2, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Unidades de Medida',
            },
        ),
    ]
