# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('biable', '0066_auto_20170213_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.IntegerField(blank=True, null=True)),
                ('mes', models.IntegerField(blank=True, null=True)),
                ('t_3_venta_neta', models.DecimalField(decimal_places=0, max_digits=10)),
                ('t_2_venta_neta', models.DecimalField(decimal_places=0, max_digits=10)),
                ('t_1_venta_neta', models.DecimalField(decimal_places=0, max_digits=10)),
                ('t_venta_neta', models.DecimalField(decimal_places=0, max_digits=10)),
                ('ciudad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biable.CiudadBiable')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biable.Cliente')),
                ('item_biable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biable.ItemsBiable')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biable.SucursalBiable')),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biable.VendedorBiable')),
            ],
        ),
    ]
