# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes_ventas', '0002_auto_20170222_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicoventa',
            name='dia_semana',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicoventa',
            name='semana',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
