# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 14:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moneda',
            options={'permissions': (('ver_tasas_actuales', 'Ver Tasas en Intranet'),), 'verbose_name_plural': '1. Monedas'},
        ),
    ]
