# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-04 21:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_auto_20170104_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='subalternos',
        ),
        migrations.AddField(
            model_name='colaborador',
            name='jefe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subalternos', to='usuarios.Colaborador'),
        ),
    ]
