# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 21:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_auto_20170104_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clienteempresa',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='clienteempresa',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='ClienteEmpresa',
        ),
    ]
