# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_auto_20170207_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextended',
            name='email_envio_como',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
