# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-02 22:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geografia_colombia', '0003_auto_20170202_1658'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pais',
            options={'verbose_name': 'País', 'verbose_name_plural': 'Paises'},
        ),
        migrations.AlterField(
            model_name='departamento',
            name='pais',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mis_departamentos', to='geografia_colombia.Pais'),
            preserve_default=False,
        ),
    ]
