# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 17:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geografia_colombia', '0004_auto_20170202_1705'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ciudad',
            unique_together=set([('nombre', 'departamento')]),
        ),
    ]
