# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 17:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geografia_colombia', '0005_auto_20170208_1231'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='departamento',
            unique_together=set([('nombre', 'pais')]),
        ),
    ]
