# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-20 19:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import productos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productos_categorias', '0001_initial'),
        ('productos_caracteristicas', '0001_initial'),
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id_cguno', models.PositiveIntegerField(default=0)),
                ('referencia', models.CharField(max_length=120, unique=True)),
                ('descripcion_estandar', models.CharField(max_length=200)),
                ('descripcion_comercial', models.CharField(max_length=200)),
                ('con_nombre_automatico', models.BooleanField(default=False, verbose_name='nombre automático')),
                ('ancho', models.CharField(default='N.A', max_length=120, verbose_name='ancho (mm)')),
                ('alto', models.CharField(default='N.A', max_length=120, verbose_name='alto (mm)')),
                ('longitud', models.CharField(default='N.A', max_length=120, verbose_name='longitud (mt)')),
                ('diametro', models.CharField(default='N.A', max_length=120, verbose_name='diametro (mm)')),
                ('cantidad_empaque', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('cantidad_minima_venta', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('costo', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('costo_cop', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('precio_base', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('rentabilidad', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('activo', models.BooleanField(default=True)),
                ('activo_componentes', models.BooleanField(default=False, verbose_name='En Compo.')),
                ('activo_proyectos', models.BooleanField(default=False, verbose_name='En Proy.')),
                ('activo_catalogo', models.BooleanField(default=False, verbose_name='En Cata.')),
                ('activo_ensamble', models.BooleanField(default=False, verbose_name='Para Ensam.')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to=productos.models.productos_upload_to, validators=[productos.models.Producto.validate_image])),
                ('categoria_dos_por_categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mis_productos', to='productos_categorias.CategoriaDosCategoria', verbose_name='categoría dos')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mis_productos', to='productos_caracteristicas.ColorProducto', verbose_name='color')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicio_created', to=settings.AUTH_USER_MODEL)),
                ('fabricante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mis_productos', to='productos_caracteristicas.FabricanteProducto', verbose_name='fabricante')),
                ('margen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos_con_margen', to='proveedores.MargenProvedor', verbose_name='Id MxC')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mis_productos', to='productos_caracteristicas.MaterialProducto', verbose_name='material')),
                ('serie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mis_productos', to='productos_caracteristicas.SerieProducto', verbose_name='serie')),
                ('tipo_por_categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mis_productos', to='productos_categorias.TipoProductoCategoría', verbose_name='tipo')),
                ('unidad_medida', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='productos_caracteristicas.UnidadMedida')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicio_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
