# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 21:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
        ('productos_caracteristicas', '0001_initial'),
        ('productos', '0002_auto_20161020_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticuloCatalogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refencia', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=200)),
                ('unidad_medida', models.CharField(max_length=100)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('costo', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('costo_cop', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('precio_base', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('rentabilidad', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('activo', models.BooleanField(default=True)),
                ('fabricante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mis_articulos_catalogo', to='productos_caracteristicas.FabricanteProducto', verbose_name='fabricante')),
                ('margen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articulos_catalogo_con_margen', to='proveedores.MargenProvedor', verbose_name='Id MxC')),
            ],
        ),
    ]
