# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 19:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_articulocatalogo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulocatalogo',
            old_name='refencia',
            new_name='referencia',
        ),
    ]
