# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 15:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_auto_20161215_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulocatalogo',
            name='costo_cop',
        ),
        migrations.RemoveField(
            model_name='articulocatalogo',
            name='precio_base',
        ),
        migrations.RemoveField(
            model_name='articulocatalogo',
            name='rentabilidad',
        ),
    ]
