# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-02 20:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_auto_20161219_1019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'Componente Banda', 'verbose_name_plural': 'Componentes Bandas'},
        ),
    ]
