# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-05 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_auto_20170102_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulocatalogo',
            name='id_cguno',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
