# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-19 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biable', '0035_itemsbiable'),
        ('productos', '0008_auto_20170105_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulocatalogo',
            name='cg_uno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mis_articulos_catalogo', to='biable.ItemsBiable', verbose_name='producto cguno'),
        ),
        migrations.AddField(
            model_name='producto',
            name='cg_uno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mis_componentes_bandas', to='biable.ItemsBiable', verbose_name='producto cguno'),
        ),
    ]
