# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-19 17:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_remove_producto_id_cguno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulocatalogo',
            name='id_cguno',
        ),
    ]
