# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0012_auto_20170228_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulocatalogo',
            name='origen',
            field=models.CharField(default='LP_INTRANET', max_length=20),
        ),
    ]
