# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 18:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0014_auto_20170314_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulocatalogo',
            name='fabricante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mis_articulos_catalogo', to='productos_caracteristicas.FabricanteProducto', verbose_name='fabricante'),
        ),
    ]
