# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 00:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ensamblado',
            name='cortado_a',
        ),
    ]
