# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0003_auto_20161020_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='banda',
            name='con_torneado_varilla',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='costoensambladoblanda',
            name='torneado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='costoensambladoblanda',
            unique_together=set([('aleta', 'empujador', 'torneado')]),
        ),
    ]
