# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 00:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0004_auto_20161020_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='banda',
            name='costo_ensamblado',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mis_bandas', to='bandas.CostoEnsambladoBlanda'),
        ),
    ]
