# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 18:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0006_auto_20161021_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banda',
            name='costo_base_total',
        ),
        migrations.RemoveField(
            model_name='banda',
            name='costo_mano_obra',
        ),
        migrations.RemoveField(
            model_name='banda',
            name='precio_banda',
        ),
        migrations.RemoveField(
            model_name='banda',
            name='precio_total',
        ),
        migrations.RemoveField(
            model_name='banda',
            name='rentabilidad',
        ),
        migrations.RemoveField(
            model_name='ensamblado',
            name='costo_cop_linea',
        ),
        migrations.RemoveField(
            model_name='ensamblado',
            name='precio_linea',
        ),
        migrations.RemoveField(
            model_name='ensamblado',
            name='rentabilidad',
        ),
    ]
