# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 19:14
from __future__ import unicode_literals

import bandas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0008_auto_20170228_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='banda',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=bandas.models.imagen_ensamblado_banda_upload_to),
        ),
    ]
