# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-16 17:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_auto_20161215_1440'),
        ('cotizaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcotizacion',
            name='articulo_catalogo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='productos.ArticuloCatalogo'),
        ),
    ]
