# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-20 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0003_auto_20161220_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remisioncotizacion',
            name='nro_factura',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='remisioncotizacion',
            name='nro_remision',
            field=models.CharField(max_length=1),
        ),
    ]
