# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-22 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0004_auto_20161220_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remisioncotizacion',
            name='nro_remision',
            field=models.CharField(max_length=10),
        ),
    ]
