# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-02 20:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0005_auto_20161222_1308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotizacion',
            options={'permissions': (('full_cotizacion', 'Full Cotizacion'), ('gestion_cotizaciones', 'Gestionar Cotizaciones'))},
        ),
    ]
