# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-05 21:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0006_auto_20170102_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcotizacion',
            name='p_n_lista_descripcion',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='itemcotizacion',
            name='p_n_lista_referencia',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='itemcotizacion',
            name='forma_pago',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items_cotizaciones', to='listasprecios.FormaPago'),
        ),
    ]
