# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-06 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0008_auto_20170106_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='observaciones',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
