# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-16 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0011_comentariocotizacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentariocotizacion',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='remisioncotizacion',
            name='nro_factura',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
