# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-16 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biable', '0034_auto_20170111_1308'),
        ('cotizaciones', '0012_auto_20170116_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remisioncotizacion',
            name='nro_factura',
        ),
        migrations.AddField(
            model_name='remisioncotizacion',
            name='factura_biable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biable.FacturasBiable'),
        ),
        migrations.AddField(
            model_name='remisioncotizacion',
            name='tipo_remision',
            field=models.CharField(default='RM', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='remisioncotizacion',
            name='nro_remision',
            field=models.PositiveIntegerField(),
        ),
    ]
