# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-17 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0013_auto_20170116_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remisioncotizacion',
            name='tipo_remision',
            field=models.CharField(choices=[('RM', 'RM'), ('RY', 'RY')], default='RM', max_length=2),
        ),
    ]
