# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-17 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0015_cotizacion_en_edicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='version',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
