# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-20 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0017_auto_20170117_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcotizacion',
            name='porcentaje_descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
