# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-20 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0019_itemcotizacion_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='descuento',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18),
        ),
    ]
