# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-20 23:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geografia_colombia', '0002_auto_20170113_1549'),
        ('cotizaciones', '0020_cotizacion_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='ciudad_despacho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geografia_colombia.Ciudad'),
        ),
    ]
