# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-31 14:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0023_auto_20170124_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mis_cotizaciones', to=settings.AUTH_USER_MODEL),
        ),
    ]
