# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-03 00:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biable', '0049_remove_movimientoventabiable_proyecto'),
        ('cotizaciones', '0024_auto_20170131_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='cliente_biable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mis_cotizaciones', to='biable.Cliente'),
        ),
    ]
