# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 20:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0025_cotizacion_cliente_biable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentariocotizacion',
            options={},
        ),
    ]
