# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0026_auto_20170206_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='ciudad',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='pais',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
