# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0027_auto_20170208_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='nro_contacto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
