# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0029_auto_20170208_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='cliente_nuevo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='otra_ciudad',
            field=models.BooleanField(default=False),
        ),
    ]
