# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 22:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cotizaciones', '0035_auto_20170215_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='creado_por',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones_creadas', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_cotizaciones', to=settings.AUTH_USER_MODEL),
        ),
    ]
