# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 22:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0036_auto_20170224_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='creado_por',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones_creadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
