# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0013_contactoempresa_cliente'),
        ('cotizaciones', '0038_auto_20170228_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='contacto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mis_cotizaciones', to='contactos.ContactoEmpresa'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='contacto_nuevo',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
