# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0040_auto_20170308_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenCotizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('imagen', models.ImageField(upload_to='')),
                ('nombre', models.CharField(max_length=20)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_imagenes', to='cotizaciones.Cotizacion')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
