# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0041_imagencotizacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagencotizacion',
            name='nombre',
        ),
    ]
