# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0044_auto_20170327_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcotizacion',
            name='cantidad_venta_perdida',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18),
        ),
    ]
