# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0045_auto_20170327_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcotizacion',
            name='cantidad_total',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18),
        ),
    ]
