# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0048_auto_20170328_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcotizacion',
            name='valor_venta_perdida_total',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18),
        ),
    ]
