# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0049_itemcotizacion_valor_venta_perdida_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='total_venta_perdida',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='itemcotizacion',
            name='cantidad_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='itemcotizacion',
            name='cantidad_venta_perdida',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='itemcotizacion',
            name='valor_venta_perdida_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
