# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0050_auto_20170328_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcotizacion',
            name='transporte_tipo',
            field=models.CharField(default='SIN DEFINIR', max_length=120),
            preserve_default=False,
        ),
    ]
