# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-10 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajo_diario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareadiaria',
            name='descripcion',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='tareadiaria',
            name='observacion',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
