# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-10 14:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trabajo_diario', '0002_auto_20170110_0852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tareadiaria',
            name='nombre',
        ),
    ]
