# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-10 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajo_diario', '0005_tareadiaria_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajodia',
            name='nro_tareas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trabajodia',
            name='nro_tareas_atendidas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trabajodia',
            name='nro_tareas_sin_atender',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
