# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-10 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajo_diario', '0006_auto_20170110_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajodia',
            name='porcentaje_atendido',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
    ]
