# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-12 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajo_diario', '0007_trabajodia_porcentaje_atendido'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareadiaria',
            name='url',
            field=models.URLField(blank=True, editable=False, max_length=300, null=True),
        ),
    ]
