# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-18 22:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trabajo_diario', '0008_tareadiaria_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trabajodia',
            options={'permissions': (('ver_trabajo_diario', 'Ver Trabajo Diario'),)},
        ),
    ]
