# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-26 18:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trabajo_diario', '0012_auto_20170126_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrabajoDiario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nro_tareas', models.PositiveIntegerField(default=0)),
                ('nro_tareas_sin_atender', models.PositiveIntegerField(default=0)),
                ('nro_tareas_atendidas', models.PositiveIntegerField(default=0)),
                ('porcentaje_atendido', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('ver_trabajo_diario', 'Ver Trabajo Diario'),),
            },
        ),
        migrations.AlterModelOptions(
            name='seguimientocartera',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='seguimientocotizacion',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='seguimientoenviotcc',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='trabajodia',
            options={},
        ),
        migrations.AddField(
            model_name='tareacartera',
            name='trabajo_diario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tareas_cartera', to='trabajo_diario.TrabajoDiario'),
        ),
        migrations.AddField(
            model_name='tareacotizacion',
            name='trabajo_diario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tareas_cotizacion', to='trabajo_diario.TrabajoDiario'),
        ),
        migrations.AddField(
            model_name='tareaenviotcc',
            name='trabajo_diario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tareas_envios_tcc', to='trabajo_diario.TrabajoDiario'),
        ),
    ]
