# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-30 22:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trabajo_diario', '0014_auto_20170126_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareacartera',
            name='trabajo_diario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tareas_cartera', to='trabajo_diario.TrabajoDiario'),
        ),
        migrations.AlterField(
            model_name='tareacotizacion',
            name='trabajo_diario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tareas_cotizacion', to='trabajo_diario.TrabajoDiario'),
        ),
        migrations.AlterField(
            model_name='tareaenviotcc',
            name='trabajo_diario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tareas_envios_tcc', to='trabajo_diario.TrabajoDiario'),
        ),
    ]
