# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-01 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajo_diario', '0015_auto_20170130_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajodiario',
            name='created',
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='trabajodiario',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
