# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-02 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajo_diario', '0016_auto_20170201_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajodiario',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
