# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 20:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trabajo_diario', '0017_auto_20170202_0946'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seguimientocartera',
            options={},
        ),
        migrations.AlterModelOptions(
            name='seguimientocotizacion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='seguimientoenviotcc',
            options={},
        ),
    ]
