# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trabajo_diario', '0018_auto_20170206_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareacotizacion',
            name='cotizacion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarea_cotizacion', to='cotizaciones.Cotizacion'),
        ),
    ]
