# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trabajo_diario', '0019_auto_20170213_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareacartera',
            name='factura',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarea_diaria_cartera', to='biable.FacturasBiable'),
        ),
        migrations.AlterField(
            model_name='tareacotizacion',
            name='cotizacion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarea_diaria_cotizacion', to='cotizaciones.Cotizacion'),
        ),
        migrations.AlterField(
            model_name='tareaenviotcc',
            name='envio',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarea_diaria_envio_tcc', to='despachos_mercancias.EnvioTransportadoraTCC'),
        ),
    ]
