# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_auto_20170228_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='factor_importacion_aereo',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=18),
        ),
    ]
