# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-20 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('canal', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'canales',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('nit', models.CharField(max_length=50, unique=True)),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empresas', to='empresas.Canal')),
            ],
            options={
                'verbose_name_plural': 'empresas',
            },
        ),
        migrations.CreateModel(
            name='GrupoEmpresarial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name_plural': 'grupos empresariales',
            },
        ),
        migrations.AddField(
            model_name='empresa',
            name='grupo_empresarial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresas', to='empresas.GrupoEmpresarial'),
        ),
    ]
