# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 21:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_auto_20170207_1619'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='canal',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='grupo_empresarial',
        ),
        migrations.DeleteModel(
            name='Empresa',
        ),
        migrations.DeleteModel(
            name='GrupoEmpresarial',
        ),
    ]
