# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_auto_20170207_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='industria',
            name='descripcion',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
