# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 20:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('biable', '0078_auto_20170302_1442'),
        ('contactos', '0013_contactoempresa_cliente'),
        ('cotizaciones', '0038_auto_20170228_0908'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trabajo_diario', '0020_auto_20170216_0902'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguimientoComercialCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('tipo_accion', models.CharField(max_length=120)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mi_seguimiento_comercial', to='biable.Cliente')),
                ('comentario_cotizacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cotizaciones.ComentarioCotizacion')),
                ('contacto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contactos.ContactoEmpresa')),
                ('cotizacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cotizaciones.Cotizacion')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mi_seguimiento_comercial', to=settings.AUTH_USER_MODEL)),
                ('seguimiento_cartera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trabajo_diario.SeguimientoCartera')),
                ('seguimiento_cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='biable.SeguimientoCliente')),
                ('seguimiento_cotizacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trabajo_diario.SeguimientoCotizacion')),
                ('seguimiento_envio_tcc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trabajo_diario.SeguimientoEnvioTCC')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
