# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 20:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguimientos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimientocomercialcliente',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mi_seguimiento_comercial', to=settings.AUTH_USER_MODEL),
        ),
    ]
