# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimientos', '0002_auto_20170302_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimientocomercialcliente',
            name='observacion_adicional',
            field=models.TextField(default='HOLA'),
            preserve_default=False,
        ),
    ]
